# Generated by Django 5.0.4 on 2024-05-15 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0006_reportcard"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="reportcard",
            unique_together={("student_rank", "date_of_report_card_generation")},
        ),
    ]
