# Generated by Django 5.0.4 on 2024-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0008_alter_reportcard_date_of_report_card_generation"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
        migrations.AddField(
            model_name="student",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
