# Generated by Django 5.0.4 on 2024-05-18 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vege", "0009_receipe_slug_student_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipe",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
